refactor ТЗ 14: добавляем бронирования и отзывы
julia-gerasimenko/java-shareit pull request #2
Opened 2023-08-24 15:09 UTC by julia-gerasimenko

2023-08-25 03:30 UTC, EugeneLenkevich requested changes
Привет, Юлия, спасибо за PR

Отличная работа, спасибо, давай только пару моментиков немножко причешем :)

2023-08-25 03:30 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +@Data
С этой аннотацией надо поаккурантей. Она генерирует equals и hashCode на основании всех полей. 
Однако, сущность - это не просто объект, это представление строки таблицы базы данных, а строку таблицы однозначно определяет ее идентификатор, и потому, соотвественно, для сущностей equals и hashCode стоит определять на основе id (первичного ключа). 

Остальные поля, при этом, могут вообще быть разными, то есть могут существовать разные версии одного и того же объекта, но как это разруливатеся - это уже отдельная история.
 
Плюс еще некоторые поля могут быть ленивыми коллекциями и в момент обращения бдут генерироваться sql-запросы, которые и не нужны в данный момент

Т.е. надо или переопределить руками или указать через аннотации как генерировать эти методы :)

2023-08-25 03:30 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (text.isBlank()) {
А text не может быть null? Лучше думаю проверочку сделать на всякий случай :)

2023-08-25 03:30 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    Collection<Item> findByNameOrDescriptionAndAvailable(@Param("text") String text);
Запрос указан через @Query, имя метода можно и сократить, такое длинное имя тяжеловато читать :)

2023-08-25 03:30 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        switch (state) {
Если есть желание можешь попробовать применить паттерн "стратегия"

Возможно, именно для этого случая стратегия покажется избыточной (обработчики все в одну строчку), но попробовать самое то, к тому же в реальной жизни часто используется, так как часто в обработчике бывает нетривиальная логика и куча своих зависимостей :) 

Смысл такой. У тебя есть соответствие между состоянием и обработчиком этого состояния.
Можно сделать мапу
Map<String, BookingStateFetchStrategy>, где BookingStateFetchStrategy - который будут реализовывать обработчики состояния

или же, более простой вариант, в мапу засунуть методы сервиса, примерно так будет
Map<String, Supplier> handlers = ...
handlers.put("ALL", this::handleAllState) 

То есть, мы заменяем switch на поиск нужного обработчика через map :)

https://ravthiru.medium.com/strategy-design-pattern-with-in-spring-boot-application-2ff5a7486cd8

2023-08-25 03:30 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/user/UserServiceDaoImpl.java
> +public class UserServiceDaoImpl implements UserService {
А зачем кстати Dao в имени сервиса, какая в этом смысловая нагрузка, еслb она неочевидно может и почикать? :)

DAO - data access object, наименование паттерна проектирования, а тут сервис :)

2023-08-25 03:30 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/user/UserServiceDaoImpl.java
> +        } catch (DataIntegrityViolationException e) {
В соседних местах используется exists-методы, может тут вместо перехвата исключения использовать их, так будет единообразно? :)

2023-08-25 15:30 UTC, julia-gerasimenko commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +@Data
спасибо, подкорректировала :)

2023-08-28 19:58 UTC, julia-gerasimenko commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        switch (state) {
К сожалению, ссылка не открывается, посмотрела на скорую руку, сделала как поняла)) не уверена, правильно ли поняла. Очень опаздываю со сдачей работ

2023-08-28 20:23 UTC, julia-gerasimenko commented on src/main/java/ru/practicum/shareit/user/UserServiceDaoImpl.java
> +        } catch (DataIntegrityViolationException e) {
есл иможно, я здесь не буду менять, это нужно создать отдельный метод лдя проверки по емейлу, я в принципе поняла, что изначально лучше делать так в одном стиле

2023-08-29 03:24 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +@Data
@EqualsAndHashCode(exclude = {"name", "description", "available", "owner"})

Лучше кстати не исключать (новое поле добавится тут его не добавят), а явно указать, так надежней 

@EqualsAndHashCode(of = {"id"})

2023-08-29 03:24 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-08-29 03:27 UTC, EugeneLenkevich requested changes
.

2023-08-29 03:40 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        switch (state) {
Ну в целом идея та, можно конечно докрутить, но нам главное понять смысл этого, получается мы разделяем описание обработки состояний от самой логики и для добавления нового состояния нам достаточно добавить новый обработчик в мапу, а не лезть в логику сопоставления, то есть тот огромный switch :)

но не будет ли бОльшая нагрузка от того, что нашему приложению нужно перебирать все бронирования пользователя

>> но не будет ли бОльшая нагрузка от того, что нашему приложению нужно перебирать все бронирования пользователя

не совсем понял причем тут наш алгоритм :)
но, если это делается на стороне БД, то это не страшно. Изначально да, СУБД будет сканировать всю таблицу, но, если мы повесим индексы на поисковые колонки, то он будет искать данные по индексу, получится чтото вроде хэшмапы, можешь погуглить про индексы СУБД

2023-08-29 03:41 UTC, EugeneLenkevich approved these changes
.

2023-08-29 21:02 UTC, merged